import {useEffect,useMemo,useRef,useState} from "react";
import {BATTERY_CAPACITIES,type BatteryCapacity} from "./battery-comparison";
import {createBatteryReportController,type BatteryRunInput,type BatteryRunState} from "./battery-report-controller";
import {adjacentBatteryDay,batteryDayWindow,expectedBatteryIntervals,selectBatteryDay,type BatteryDay,type BatteryDayDetail} from "./battery-daily-report";
import type {BatteryIntervalObservation} from "@crems/core/battery-simulation";

const number=(value:number)=>value.toLocaleString("nl-BE",{maximumFractionDigits:2});
const time=(instant:string)=>new Date(instant).toLocaleTimeString("nl-BE",{timeZone:"Europe/Brussels",hour:"2-digit",minute:"2-digit",timeZoneName:"shortOffset"});
const colors={source:"#50d5ed",export:"#6b9fff",charge:"#ffae52",discharge:"#4fe0a8",soc:"#b894ff"};
type Series={name:string;color:string;value:(p:BatteryIntervalObservation)=>number};

function IntervalChart({title,points,day,series,soc=false}:{title:string;points:BatteryIntervalObservation[];day:string;series:Series[];soc?:boolean}){
  const window=batteryDayWindow(day),start=Date.parse(window.start),end=Date.parse(window.end),max=Math.max(1,...points.flatMap(p=>series.map(s=>s.value(p))),...(soc?points.map(p=>p.startStoredKwh):[]));
  const x=(t:string)=>48+(Date.parse(t)-start)/(end-start)*520,y=(n:number)=>160-n/max*130;
  return <article className="daily-chart"><h3>{title}</h3><div className="daily-legend">{series.map(s=><span key={s.name}><i style={{background:s.color}}/>{s.name}</span>)}<span>{soc?"kWh in batterij":"kWh per kwartier"}</span></div><svg viewBox="0 0 600 200" role="img" aria-label={`${title}, ${day}, ${soc?"kWh in batterij":"kWh per kwartier"}, Europe/Brussels; gaten blijven leeg`}>
    {[0,.5,1].map(f=><g key={f}><line x1="48" x2="568" y1={y(max*f)} y2={y(max*f)} className="daily-grid"/><text x="42" y={y(max*f)+4} textAnchor="end">{number(max*f)}</text></g>)}
    {[0,.25,.5,.75,1].map(f=><text key={f} x={48+520*f} y="182" textAnchor={f===0?"start":f===1?"end":"middle"}>{time(new Date(start+(end-start)*f).toISOString())}</text>)}
    {points.map(p=><g key={p.start}>{series.map((s,i)=>soc?<path key={s.name} d={`M ${x(p.start)} ${y(p.startStoredKwh-p.resetLossKwh)} H ${x(p.end)} V ${y(s.value(p))}`} fill="none" stroke={s.color} strokeWidth="2"><title>{time(p.start)}: {number(s.value(p))} kWh{p.gap?" · gat vóór dit kwartier":""}</title></path>:<rect key={s.name} x={x(p.start)+(x(p.end)-x(p.start))*i/series.length} y={y(s.value(p))} width={Math.max(.2,(x(p.end)-x(p.start))/series.length-.4)} height={160-y(s.value(p))} fill={s.color} opacity={p.estimated?.55:.9}><title>{time(p.start)} · {s.name}: {number(s.value(p))} kWh{p.estimated?" · geschat":""}</title></rect>)}</g>)}
  </svg></article>;
}

export function BatteryDailyReport({days,initialDetail,source,onChooseSource,onReleaseInitialDetail}:{days:BatteryDay[]|undefined;initialDetail?:BatteryDayDetail;source?:BatteryRunInput;onChooseSource:()=>void;onReleaseInitialDetail?:()=>void}){
  const [selectedDay,setSelectedDay]=useState(days?.[0]?.day??"");const [capacity,setCapacity]=useState<BatteryCapacity>(3);
  const [detailRequest,setDetailRequest]=useState(0);
  const dayLengths=useMemo(()=>new Map(days?.map(d=>[d.day,expectedBatteryIntervals(d.day)])??[]),[days]);
  const day=days?.length&&selectedDay>=days[0]!.day&&selectedDay<=days.at(-1)!.day?selectedDay:days?.[0]?.day??"";
  const [replay,setReplay]=useState<{day:string;source?:BatteryRunInput;state:BatteryRunState}>({day:"",state:{status:"idle"}});
  const controllerRef=useRef<ReturnType<typeof createBatteryReportController>|undefined>(undefined);
  useEffect(()=>{
    if(!source||!day||initialDetail?.day===day||!detailRequest)return;
    const controller=createBatteryReportController({loadPrices:async()=>undefined,publish:state=>setReplay({day,source,state})});controllerRef.current=controller;
    void controller.run(source,{day,skipPrices:true});return()=>{controller.dispose();if(controllerRef.current===controller)controllerRef.current=undefined;};
  },[source,day,initialDetail,detailRequest]);
  if(!days?.length)return <section className="battery-daily"><p className="eyebrow">Dagrapport</p><h2>Controleer wat de batterij elke dag doet</h2><p>Dit oudere rapport bevat nog geen dagdata. Kies je CSV om lokaal een nieuw dagrapport te berekenen. Het bewaarde rapport blijft staan tot je het nieuwe resultaat expliciet bewaart.</p><button className="primary" onClick={onChooseSource}>Kies CSV voor dagrapport</button></section>;
  const {selected,energy}=selectBatteryDay(days,day,capacity);
  const replayDetail=replay.source===source&&replay.day===day&&replay.state.status==="success"?replay.state.detail:undefined;
  const detail=initialDetail?.day===day?initialDetail:replayDetail;
  const points=detail?.candidates.find(c=>c.capacityKwh===capacity)?.points;
  const first=days[0]!.day,last=days.at(-1)!.day;
  const max=Math.max(1,...days.map(d=>d.candidates.find(c=>c.capacityKwh===capacity)!.dischargedKwh));
  const rangeStart=Date.parse(`${first}T12:00:00Z`),rangeEnd=Date.parse(`${last}T12:00:00Z`)+86400000;
  const overviewX=(d:string)=>48+(Date.parse(`${d}T12:00:00Z`)-rangeStart)/(rangeEnd-rangeStart)*820;
  const dayWidth=Math.max(.5,820*86400000/(rangeEnd-rangeStart)-1);
  const choose=(value:string)=>{if(value>=first&&value<=last){if(value!==day){if(initialDetail)onReleaseInitialDetail?.();setReplay({day:value,state:{status:"idle"}});}setSelectedDay(value);setDetailRequest(current=>current+1);}};
  const missing=selected?selected.count<dayLengths.get(day)!||selected.gapCount>0:true;
  const dayMax=Math.max(1,...(selected?.candidates.flatMap(c=>[c.sourceImportKwh,c.sourceImportKwh-c.dischargedKwh])??[]));
  return <section className="battery-daily" aria-label="Interactief batterij-dagrapport"><div className="daily-heading"><div><p className="eyebrow">Controleer je batterijscenario</p><h2>Elke dag in beeld</h2><p>Dagtotalen en kwartierdetail · Europe/Brussels · simulatie op gemeten of geschatte brondata</p></div><span className="pill">{days.length} dagen met data</span></div>
    <div className="daily-filters"><button aria-label="Vorige dag" disabled={day<=first} onClick={()=>choose(adjacentBatteryDay(day,-1))}>←</button><label>Dag<input type="date" min={first} max={last} value={day} onChange={e=>choose(e.target.value)}/></label><button aria-label="Volgende dag" disabled={day>=last} onClick={()=>choose(adjacentBatteryDay(day,1))}>→</button><label>Batterij<select value={capacity} onChange={e=>setCapacity(Number(e.target.value) as BatteryCapacity)}>{BATTERY_CAPACITIES.map(c=><option key={c} value={c}>{c} kWh · {number(c/2)} kW</option>)}</select></label><span className="daily-selection" role="status">{day} · {capacity} kWh</span></div>
    {!selected?<p className="chart-warning" role="status">Geen brondata voor deze dag. De waarden en grafieken blijven leeg.</p>:<><div className="daily-kpis">{[["Bronafname",energy!.sourceImportKwh],["Broninjectie",energy!.sourceExportKwh],["Batterij laden",energy!.chargedKwh],["Batterij ontladen",energy!.dischargedKwh],["Afname met batterij",energy!.sourceImportKwh-energy!.dischargedKwh],["Eindlading",energy!.endStoredKwh]].map(([label,value])=><article key={String(label)}><span>{label}</span><strong>{number(value as number)} <small>kWh</small></strong></article>)}</div><p className={missing||selected.estimatedCount?"chart-warning":"price-note"}>{selected.count}/{dayLengths.get(day)} kwartieren · {selected.estimatedCount} geschat · {selected.gapCount} gaten{missing?" · onvolledig: ontbrekende kwartieren zijn geen nulmeting":" · volledige dag"}. {number(energy!.conversionLossKwh)} kWh conversieverlies · {number(energy!.resetLossKwh)} kWh vervallen door gaten.</p></>}
    <article className="daily-chart daily-overview"><h3>Vermeden netafname per dag · {capacity} kWh batterij</h3><p>Kies een dag in de grafiek of met de datumkiezer. Lege plaatsen betekenen ontbrekende dagen.</p><svg viewBox="0 0 900 180" role="group" aria-label={`Dagtotalen vermeden netafname, ${capacity} kWh batterij, kWh per dag`}><line x1="48" x2="868" y1="142" y2="142" className="daily-grid"/><text x="42" y="25" textAnchor="end">{number(max)}</text><text x="42" y="145" textAnchor="end">0</text>{days.map(d=><rect key={d.day} role="button" tabIndex={0} aria-label={`Selecteer ${d.day}`} onClick={()=>choose(d.day)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();choose(d.day);}}} x={overviewX(d.day)} y={142-d.candidates.find(c=>c.capacityKwh===capacity)!.dischargedKwh/max*115} width={dayWidth} height={Math.max(2,d.candidates.find(c=>c.capacityKwh===capacity)!.dischargedKwh/max*115)} fill={d.day===day?colors.charge:colors.discharge} opacity={d.estimatedCount||d.count<dayLengths.get(d.day)!?.5:1}><title>{d.day}: {number(d.candidates.find(c=>c.capacityKwh===capacity)!.dischargedKwh)} kWh{d.estimatedCount?" · geschat":""}</title></rect>)}<text x="48" y="166">{first}</text><text x="868" y="166" textAnchor="end">{last}</text></svg></article>
    {selected&&<article className="daily-chart"><h3>Vergelijk capaciteiten op {day}</h3><div className="daily-legend"><span><i style={{background:colors.source}}/>Bronafname zonder batterij</span><span><i style={{background:colors.discharge}}/>Afname met batterij</span><span>kWh per dag · kies een capaciteit</span></div><svg viewBox="0 0 600 190" role="group" aria-label={`Batterijvergelijking ${day}`}><text x="42" y="25" textAnchor="end">{number(dayMax)}</text><text x="42" y="145" textAnchor="end">0</text>{selected.candidates.map((c,i)=><g key={c.capacityKwh} role="button" tabIndex={0} aria-label={`Selecteer ${c.capacityKwh} kWh`} onClick={()=>setCapacity(c.capacityKwh)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();setCapacity(c.capacityKwh);}}}><rect x={60+i*104} y="12" width="88" height="166" fill="transparent" stroke={c.capacityKwh===capacity?colors.soc:"transparent"} rx="6"/>{[c.sourceImportKwh,c.sourceImportKwh-c.dischargedKwh].map((value,j)=><rect key={j} x={77+i*104+j*25} y={142-value/dayMax*115} width="23" height={value/dayMax*115} fill={j?colors.discharge:colors.source}><title>{number(value)} kWh</title></rect>)}<text x={104+i*104} y="164" textAnchor="middle">{c.capacityKwh} kWh</text></g>)}</svg></article>}
    <div className="daily-detail-heading"><h3>Binnen de dag · {day} · {capacity} kWh</h3>{source&&replay.day===day&&replay.state.status==="running"&&<span role="status">Bron lokaal herlezen… {replay.state.progress}% <button onClick={()=>controllerRef.current?.cancel()}>Annuleren</button></span>}</div>
    {source&&!points&&!(replay.day===day&&replay.state.status==="running")&&<button onClick={()=>setDetailRequest(current=>current+1)}>Toon kwartierdetail</button>}
    {!source&&!points&&<p className="chart-warning">Dagtotalen zijn bewaard. Voor grafieken binnen de dag is het bronbestand nodig; kwartiergegevens worden nooit opgeslagen. <button onClick={onChooseSource}>Kies CSV voor dagdetail</button></p>}
    {replay.day===day&&replay.state.status==="error"&&<p role="alert">Het dagdetail kon niet worden gelezen. Kies het bronbestand opnieuw.</p>}
    {points?.length?<><div className="daily-plots"><IntervalChart title="Bronafname en broninjectie" points={points} day={day} series={[{name:"Bronafname",color:colors.source,value:p=>p.sourceImportKwh},{name:"Broninjectie",color:colors.export,value:p=>p.sourceExportKwh}]}/><IntervalChart title="Batterij laden en ontladen" points={points} day={day} series={[{name:"Laden",color:colors.charge,value:p=>p.chargedKwh},{name:"Ontladen",color:colors.discharge,value:p=>p.dischargedKwh}]}/><IntervalChart title="Afname zonder en met batterij" points={points} day={day} series={[{name:"Zonder batterij",color:colors.source,value:p=>p.sourceImportKwh},{name:"Met batterij",color:colors.discharge,value:p=>p.sourceImportKwh-p.dischargedKwh}]}/><IntervalChart title="Laadniveau batterij" points={points} day={day} soc series={[{name:"Laadniveau",color:colors.soc,value:p=>p.endStoredKwh}]}/></div><details className="daily-table"><summary>Controleer de kwartierwaarden ({points.length})</summary><div><table><caption>{day} · {capacity} kWh · alle energiewaarden in kWh</caption><thead><tr>{["Tijd (Brussel)","Afname","Injectie","Laden","Ontladen","Afname na batterij","Laadniveau einde","Kwaliteit"].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{points.map(p=><tr key={p.start}><th>{time(p.start)}</th>{[p.sourceImportKwh,p.sourceExportKwh,p.chargedKwh,p.dischargedKwh,p.sourceImportKwh-p.dischargedKwh,p.endStoredKwh].map((v,i)=><td key={i}>{number(v)}</td>)}<td>{p.estimated?"Geschat":"Gemeten"}{p.gap?" · gat ervoor":""}</td></tr>)}</tbody></table></div></details></>:selected&&source&&replay.day===day&&replay.state.status==="success"&&<p>Geen kwartierdetail voor deze dag.</p>}
    {selected&&<details className="daily-table"><summary>Controleer dagtotalen en energiebalans</summary><div><table><caption>{day} · kWh · begin + laden − ontladen − conversie − gatverlies = einde</caption><thead><tr>{["Batterij","Begin","Laden","Ontladen","Conversie","Gatverlies","Einde"].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{selected.candidates.map(c=><tr key={c.capacityKwh}><th>{c.capacityKwh} kWh</th>{[c.startStoredKwh,c.chargedKwh,c.dischargedKwh,c.conversionLossKwh,c.resetLossKwh,c.endStoredKwh].map((v,i)=><td key={i}>{number(v)}</td>)}</tr>)}</tbody></table></div></details>}
    <p className="price-note">Lading loopt over middernacht door. Dagdetail herleest de voorgaande historie, zodat de beginlading klopt. Een gat verbreekt de grafiek en maakt de batterij conservatief leeg; ontbrekende energie wordt niet verzonnen. De simulator verrekent gelijktijdige afname en injectie vóór laden/ontladen.</p>
  </section>;
}
