import type { ParsedCsv } from "./csv.js";

export const FLUVIUS_HEADERS = ["Van (datum)","Van (tijdstip)","Tot (datum)","Tot (tijdstip)","EAN-code","Meter","Metertype","Register","Volume","Eenheid","Validatiestatus","Omschrijving"] as const;
export class FluviusSchemaError extends Error { readonly code="INVALID_FLUVIUS_SCHEMA" as const; constructor(){super("Fluvius-schema is ongeldig");} }
export type FluviusInterval={start:string;end:string;direction:"import"|"export";register:"day"|"night";energyKwh:number;quality:"measured"|"estimated"|"noConsumption"};
export type FluviusReason="INVALID_DATE_TIME"|"INVALID_INTERVAL"|"INVALID_VALUE"|"INVALID_UNIT"|"INVALID_REGISTER"|"INVALID_STATUS";
export type FluviusMapResult={intervals:FluviusInterval[];skippedCount:number;reasons:Record<FluviusReason,number>;skippedRows:number[];measuredCount:number;estimatedCount:number;noConsumptionCount:number;gapCount:number;duplicateCount:number;overlapCount:number;importKwh:number;exportKwh:number;measuredImportKwh:number;estimatedImportKwh:number;measuredExportKwh:number;estimatedExportKwh:number};
const formatter=new Intl.DateTimeFormat("en-GB",{timeZone:"Europe/Brussels",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hourCycle:"h23"});
const localKey=(date:Date)=>{const p=Object.fromEntries(formatter.formatToParts(date).map(x=>[x.type,x.value]));return `${p.day}-${p.month}-${p.year} ${p.hour}:${p.minute}:${p.second}`;};
const candidates=(date:string,time:string)=>{if(!/^\d{2}-\d{2}-\d{4}$/.test(date)||!/^\d{2}:\d{2}(?::\d{2})?$/.test(time))return[];const [d,m,y]=date.split("-").map(Number);const [h,min,sec=0]=time.split(":").map(Number);if(h!>23||min!>59||sec>59)return[];const normalized=`${date} ${String(h).padStart(2,"0")}:${String(min).padStart(2,"0")}:${String(sec).padStart(2,"0")}`;const center=Date.UTC(y!,m!-1,d!,h!,min!,sec);return [2,1].map(offsetHours=>center-offsetHours*3600000).filter(ms=>localKey(new Date(ms))===normalized);};
const registers:Record<string,["import"|"export","day"|"night"]>={"Afname Dag":["import","day"],"Afname Nacht":["import","night"],"Injectie Dag":["export","day"],"Injectie Nacht":["export","night"]};
const qualities:Record<string,FluviusInterval["quality"]>={Uitgelezen:"measured",Geschat:"estimated","Geen verbruik":"noConsumption"};
export const mapFluviusQuarterHours=(csv:Readonly<ParsedCsv>):FluviusMapResult=>{
 if(csv.delimiter!==";"||csv.headers.length!==FLUVIUS_HEADERS.length||csv.headers.some((h,i)=>h!==FLUVIUS_HEADERS[i]))throw new FluviusSchemaError();
 const reasons:Record<FluviusReason,number>={INVALID_DATE_TIME:0,INVALID_INTERVAL:0,INVALID_VALUE:0,INVALID_UNIT:0,INVALID_REGISTER:0,INVALID_STATUS:0};const skippedRows:number[]=[];const intervals:FluviusInterval[]=[];const seenLocal=new Map<string,number>();const candidateCache=new Map<string,number[]>();const cachedCandidates=(date:string,time:string)=>{const key=`${date}|${time}`;const cached=candidateCache.get(key);if(cached)return cached;const value=candidates(date,time);candidateCache.set(key,value);return value;};
 const skip=(reason:FluviusReason,row:number)=>{reasons[reason]+=1;skippedRows.push(row);};
 csv.rows.forEach((values,index)=>{const row=index+2;const register=registers[values[7]!.trim()];if(!register){skip("INVALID_REGISTER",row);return;}const startOptions=cachedCandidates(values[0]!,values[1]!);const endOptions=cachedCandidates(values[2]!,values[3]!);if(!startOptions.length||!endOptions.length){skip("INVALID_DATE_TIME",row);return;}const local=`${register[0]}:${register[1]}:${values[0]} ${values[1]}`;const occurrence=seenLocal.get(local)??0;seenLocal.set(local,occurrence+1);const start=startOptions[Math.min(occurrence,startOptions.length-1)]!;const end=endOptions.find(value=>value>start)??endOptions.at(-1)!;if(end-start!==15*60000){skip("INVALID_INTERVAL",row);return;}if(values[9]!.trim()!=="kWh"){skip("INVALID_UNIT",row);return;}const quality=qualities[values[10]!.trim()];if(!quality){skip("INVALID_STATUS",row);return;}const raw=values[8]!.trim();const energy=quality==="noConsumption"&&raw===""?0:/^\d+(?:,\d+)?$/.test(raw)?Number(raw.replace(",",".")):Number.NaN;if(!Number.isFinite(energy)||energy<0){skip("INVALID_VALUE",row);return;}intervals.push({start:new Date(start).toISOString(),end:new Date(end).toISOString(),direction:register[0],register:register[1],energyKwh:energy,quality});});
 intervals.sort((a,b)=>Date.parse(a.start)-Date.parse(b.start));let gapCount=0,duplicateCount=0,overlapCount=0;const previous=new Map<string,FluviusInterval>();for(const item of intervals){const key=`${item.direction}:${item.register}`;const before=previous.get(key);if(before){const delta=Date.parse(item.start)-Date.parse(before.end);if(delta>0)gapCount+=1;else if(delta<0)overlapCount+=1;if(item.start===before.start&&item.end===before.end)duplicateCount+=1;}previous.set(key,item);}
 const total=(direction:"import"|"export",quality?:FluviusInterval["quality"])=>intervals.filter(x=>x.direction===direction&&(!quality||x.quality===quality)).reduce((n,x)=>n+x.energyKwh,0);return{intervals,skippedCount:skippedRows.length,reasons,skippedRows,measuredCount:intervals.filter(x=>x.quality==="measured").length,estimatedCount:intervals.filter(x=>x.quality==="estimated").length,noConsumptionCount:intervals.filter(x=>x.quality==="noConsumption").length,gapCount,duplicateCount,overlapCount,importKwh:total("import"),exportKwh:total("export"),measuredImportKwh:total("import","measured"),estimatedImportKwh:total("import","estimated"),measuredExportKwh:total("export","measured"),estimatedExportKwh:total("export","estimated")};
};
